name: e2e

# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on: [push, deployment, deployment_status]

# Cancel previously running jobs
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  e2e:
    # only runs this job on successful deploy
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
      - name: Setup Node.js & Yarn
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          # cache: "yarn"
      # Run Cypress
      - name: Run Cypress 🌲
        uses: cypress-io/github-action@v6
        with:
          install-command: yarn install # --immutable
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
