# This is a basic workflow to help you get started with Actions

name: Prettier/TS/Lint/Jest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Node.js & Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      # Cache node_modules
      - name: Cache node_modules
        id: cache-yarn
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      # Install dependencies only when yarn.lock changes
      - name: Install dependencies
        if: steps.cache-yarn.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Run prettier
        run: yarn prettier
      - name: Run type check
        run: yarn type-check
      - name: Run linter
        run: yarn lint
      - name: Run tests
        run: yarn test
